"""add indexes and constraints

Revision ID: 29ba77b15785
Revises: 
Create Date: 2026-07-10 15:26:37.070240

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '29ba77b15785'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audio_transcriptions', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.create_index('ix_consent_patient_professional', 'consents', ['patient_id', 'professional_id'], unique=False)
    op.create_index('ix_emotional_analysis_entry', 'emotional_analyses', ['entry_id'], unique=False)
    op.create_index('ix_emotional_analysis_risk', 'emotional_analyses', ['risk_level'], unique=False)
    op.create_index('ix_entries_patient_created', 'emotional_entries', ['patient_id', 'created_at'], unique=False)
    op.create_index('ix_entries_patient_type', 'emotional_entries', ['patient_id', 'entry_type'], unique=False)
    op.create_index('ix_link_request_patient_professional_status', 'link_requests', ['patient_id', 'professional_id', 'status'], unique=False)
    op.create_index('ix_notifications_user_read', 'notifications', ['user_id', 'is_read'], unique=False)
    op.create_index('ix_patient_professional_patient_professional', 'patient_professionals', ['patient_id', 'professional_id'], unique=False)
    op.create_index('ix_patient_professional_professional', 'patient_professionals', ['professional_id'], unique=False)
    op.create_index('ix_patient_recommendation_analysis', 'patient_recommendations', ['analysis_id'], unique=True)
    op.create_index('ix_patient_recommendation_patient', 'patient_recommendations', ['patient_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_patient_recommendation_patient', table_name='patient_recommendations')
    op.drop_index('ix_patient_recommendation_analysis', table_name='patient_recommendations')
    op.drop_index('ix_patient_professional_professional', table_name='patient_professionals')
    op.drop_index('ix_patient_professional_patient_professional', table_name='patient_professionals')
    op.drop_index('ix_notifications_user_read', table_name='notifications')
    op.drop_index('ix_link_request_patient_professional_status', table_name='link_requests')
    op.drop_index('ix_entries_patient_type', table_name='emotional_entries')
    op.drop_index('ix_entries_patient_created', table_name='emotional_entries')
    op.drop_index('ix_emotional_analysis_risk', table_name='emotional_analyses')
    op.drop_index('ix_emotional_analysis_entry', table_name='emotional_analyses')
    op.drop_index('ix_consent_patient_professional', table_name='consents')
    op.drop_column('audio_transcriptions', 'updated_at')
    # ### end Alembic commands ###
