"""add provider y model de la ia

Revision ID: d226ac7620a0
Revises: 29ba77b15785
Create Date: 2026-07-14 15:14:36.707864

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd226ac7620a0'
down_revision: Union[str, Sequence[str], None] = '29ba77b15785'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""

    op.add_column(
        "emotional_analyses",
        sa.Column(
            "provider",
            sa.String(),
            nullable=False,
            server_default="UNKNOWN"
        )
    )

    op.add_column(
        "emotional_analyses",
        sa.Column(
            "model",
            sa.String(),
            nullable=False,
            server_default="UNKNOWN"
        )
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('emotional_analyses', 'model')
    op.drop_column('emotional_analyses', 'provider')
    # ### end Alembic commands ###
